name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - requests=2.24.0
  - scikit-learn=0.24
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - git+https://github.com/yujinine/Project-Build-an-ML-Pipeline-Starter6.git#egg=wandb-utils&subdirectory=components
