name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.3.1
  - requests=2.24.0
  - scikit-learn=0.24
  - pandas=2.1.3
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - git+https://github.com/yujinine/Project-Build-an-ML-Pipeline-Starter6.git#egg=wandb-utils&subdirectory=components
      - databricks_cli==0.8.7
